server:
  port: 8989
  servlet:
    context-path: /
    application-display-name: sms
spring:
  application:
    name: sms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/sms?characterEncoding=utf8
    username: root
    password: root
  redis:
    host: 192.168.56.10
    port: 6379
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 4MB
      
mybatis:
  mapper-locations: classpath:/mapper/sms/*.xml
  type-aliases-package: com.jackeyj.sms.entity

logging:
  level:
    com:
      jackeyj:
        sms:
          dao: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true

